name: build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    env:
      WINE_SHMBRIDGE_LINK: https://github.com/Yellow-Dog-Man/Wine-ShmBridge/releases/download/1.0.0/shmbridge.dll.so
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
    name: Build and Test on ${{ matrix.os }}

    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            9.0.x

      - if: runner.os == 'Linux'
        name: Setup Mono runtime
        run: |
          sudo gpg --homedir /tmp --no-default-keyring --keyring /usr/share/keyrings/mono-official-archive-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
          echo "deb [signed-by=/usr/share/keyrings/mono-official-archive-keyring.gpg] https://download.mono-project.com/repo/debian stable-buster main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
          sudo apt install dirmngr ca-certificates gnupg
          sudo apt update
          sudo apt install mono-complete

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      
      - if: runner.os == 'Linux'
        name: Fetch Wine-ShmBridge
        run: wget --content-disposition -P "src/Interprocess/runtimes/win-x64/native" "${{env.WINE_SHMBRIDGE_LINK}}"

      - if: runner.os == 'Windows'
        name: Fetch Wine-ShmBridge
        run: Invoke-WebRequest "${{env.WINE_SHMBRIDGE_LINK}}" -OutFile .\src\Interprocess\runtimes\win-x64\native\shmbridge.dll.so

      - name: Build and Test
        run: dotnet test src/Interprocess.sln

      - name: Build - Release
        run: dotnet build -c Release src/Interprocess.sln

      - name: Pack
        run: dotnet pack -c Release --no-build --output . --version-suffix ${{github.run_number}} src/Interprocess/Interprocess.csproj

      - name: Put a big red bow on it
        uses: actions/upload-artifact@v4
        with:
          name: Interprocess-${{runner.os}}
          path: src/Interprocess/bin/Release/*.nupkg